/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedGerenteRouteImport } from './routes/_authenticated/gerente'
import { Route as AuthenticatedAtendenteRouteImport } from './routes/_authenticated/atendente'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGerenteRoute = AuthenticatedGerenteRouteImport.update({
  id: '/gerente',
  path: '/gerente',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAtendenteRoute = AuthenticatedAtendenteRouteImport.update({
  id: '/atendente',
  path: '/atendente',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/atendente': typeof AuthenticatedAtendenteRoute
  '/gerente': typeof AuthenticatedGerenteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/atendente': typeof AuthenticatedAtendenteRoute
  '/gerente': typeof AuthenticatedGerenteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/_authenticated/atendente': typeof AuthenticatedAtendenteRoute
  '/_authenticated/gerente': typeof AuthenticatedGerenteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/app' | '/login' | '/atendente' | '/gerente'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app' | '/login' | '/atendente' | '/gerente'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/app'
    | '/login'
    | '/_authenticated/atendente'
    | '/_authenticated/gerente'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AppRoute: typeof AppRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/gerente': {
      id: '/_authenticated/gerente'
      path: '/gerente'
      fullPath: '/gerente'
      preLoaderRoute: typeof AuthenticatedGerenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atendente': {
      id: '/_authenticated/atendente'
      path: '/atendente'
      fullPath: '/atendente'
      preLoaderRoute: typeof AuthenticatedAtendenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAtendenteRoute: typeof AuthenticatedAtendenteRoute
  AuthenticatedGerenteRoute: typeof AuthenticatedGerenteRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAtendenteRoute: AuthenticatedAtendenteRoute,
  AuthenticatedGerenteRoute: AuthenticatedGerenteRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AppRoute: AppRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
